### ISSUE TITLE
Ideas for improving the player

### ISSUE THREAD

**Issue by Kennard123661** [CS3243-AY1718S2-13/Tetris-Player#6]
1. **Use selective extension to search k best simulated states one/two plys deeper and get the one that has the best expected value.** (I would suggest 3 - implement by creating PQ and updating values of 3 best states - either use a linkedlist or something to hold the values - linkedlist because can remove-first/last easier also) 
    * I would suggest only searching one ply deeper (a second ply deeper would take up more time - harder to test and optimize).
    * Also, when calculating the deeper ply for the algorithm, for each piece, get the maximum value for each orientation and slot. Then, to get the expected value (either you get the minimum value out of all 7 pieces, (cuz we might a really shitty piece) or you sum the (sqrt of each calculated value) before multiplying by 1/7. (sqrt so you reduce the effects of really good moves, and helps the game consider weaker moves as well). (i.e. one really good move for a piece could outweight shitty moves for the 6 other pieces).

2. **Update the glitchCount heuristic so that it penalizes for consecutvie glitches/holes (only certain pieces can solve those).**

3. **(A LOT OF EFFORT) Create training sets, for each state and each move, then we train the algorithm using reinforcement learning to train its weights, otherwise, we can create a connecting states of the board, then its weight updated with each training set.** - We can encode board states using NUM OF ROWS of Integers, each integer is the binary encoding of a row i.e. 0010100110 etc. 

4. **Add a cost function that takes into account the cost of solving a well** Refer to this pdf 
[Breelyn_Eric_Don_Project.pdf](https://github.com/CS3243-AY1718S2-13/Tetris-Player/files/1761693/Breelyn_Eric_Don_Project.pdf)

5. **Do more research and include your suggestions here**

**Comment by khooroko** [comment]
Increase efficiency by:

1. Killing off any candidate with min rows cleared less than a fixed number (maybe 100 for now)
2. Cutting off simulation at a fixed number of moves (perhaps 1000) with a score for number of rows cleared and the state of the board (total height and number of glitches etc) taken at fixed intervals, and using the sum of these scores to compare between runs instead of what we are doing now, which is to see how many rows are cleared by game over.
